python3 stereo_evaluator.py --name greaten-selective-stereo \
--logdir ./experiments/greaten_stereo/selective-based/sceneflow/baseline \
--backbone_type vitl \
--backbone_ckpt ./experiments/modules/backbones/depth_anything/depth_anything_v2_vitl.pth \
--dataset sceneflow \
--dataset_root ~/Workspace/Researches/Datasets/SceneFlow \
--restore_ckpt ./greaten-selective-stereo.pth \
--eval_mode metric \
--eval_iters 32 \
--cv_levels 2 \
--cv_radius 4 \
--n_downsample 2 \
--n_gru_layers 3 \
--channels 128 128 128 \
--context_norm batch \
--max_disp 192 \
--infer_normal
